sudo: required
services:
  - docker

before_install:
  - docker build -t henriqueamitay/frontend-test -f Dockerfile.dev .

script:
  - docker run henriqueamitay/frontend-test npm run test -- --coverage