sudo: required
services:
  - docker

before_install:
  - docker build -t henriqueamitay/frontend-test -f Dockerfile.dev .

script:
  - docker run henriqueamitay/frontend-test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app : "udemy-docker"
  env: "UdemyDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-090871912695"
  bucket_path: "udemy-docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
